### ISSUE TITLE
Weird reading

### ISSUE THREAD

**Issue by GawiQ** [owainm713/LIS3DH-Python-Module#1]
Hi 
I'm new to all this and need some help. I managed to connect to the accelerometer via SPI but the reading I get looks like this:
x: 128 y: 0 z: 256
x: 128 y: 0 z: 0
x: 256 y: 0 z: 256

What do I have to do to make it look more normal - preferably decimal values in g's? 
The numbers in reading I get change randomly and they don't seem to react to movement.
I2C connection works better - it reacts to movement but instead of 1g it shows something around 130.
Cheers

**Comment by owainm713** [comment]
Hi, the x,y,z values provided are the raw values from the accelerometer's adc, being 10 bit adc's, 2 complement with sign bit you will see values between -512 and 511, With the accelerometer scale set at +-2g, the default, a value of 256 indicates +1g , being half of the positive scale.  

Let me know if that helps

**Comment by GawiQ** [comment]
Hi, thanks for the reply
But, like I said, the reading I get does not seem to be affected by any movement of the sensor. The numbers just change randomly even without moving. And the reading never or rarely gives number other than 0; 128; 256 or something close. Does it mean that I would only get the 0; 0,5 and 1g reading and nothing in between?

**Comment by owainm713** [comment]
HI

No you should be getting readings throughout the range -512 to 511 when you move the sensor about. How do you have you it hooked up?,  are you using an adafruit, Sparkfun or other LIS3DH board.  What does your program look like?

**Comment by owainm713** [comment]
So for SPI, I have to add a statement to explicitly set the speed of the connection.  Recent Pi updates has done something to make this required.  Ill try to do that in the next day or so.

**Comment by owainm713** [comment]
Added SPI fix

**Comment by GawiQ** [comment]
Thank you
Still, the reading I get after this gives only 0's on every axle. It looks like this:
x: 0.0 y: 0.0 z: 0.0 
x: 0.0 y: 0.0 z: 0.0 
x: 0.0 y: 0.0 z: 0.0
x: 0.0 y: 0.0 z: 0.0 
x: 0.0 y: 0.0 z: 0.0 
x: 0.0 y: 0.0 z: 0.0

**Comment by GawiQ** [comment]
Seems to me that something is wrong with single acces write and read definitions for SPI. 
I managed to implement a similar code in C based on yours for I2C and it works fine. I suspected two's complement conversion to be bad but like I said - I2C works

**Comment by GawiQ** [comment]
The code I'm using looks like this:

`#!/usr/bin/python

import LIS3DH_new
import time, spidev, sys

#accel = LIS3DH.Accelerometer('i2c',i2cAddress = 0x19)
accel = LIS3DH_new.Accelerometer('spi', spiPort = 0, spiCS = 0)  # spi connection alternative
accel.set_ODR(odr=50, powerMode='normal')
accel.axis_enable(x='on',y='on',z='on')
accel.interrupt_high_low('high')
accel.latch_interrupt('on')
accel.set_BDU('on')
accel.set_scale()


    #----------  Raw X,Y, Z data output -----------------
t_end = time.time() + 1 
while time.time() < t_end:
        x = accel.x_axis_reading()
        y = accel.y_axis_reading()
        z = accel.z_axis_reading()
        print ('x: '+str(x)+' y: '+str(y)+' z: '+str(z))`

Where 'LIS3DH_new' is is your LIS3DH.py after the fix.

**Comment by GawiQ** [comment]
The code I'm using looks like this:

`#!/usr/bin/python

import LIS3DH_new
import time, spidev, sys

#accel = LIS3DH.Accelerometer('i2c',i2cAddress = 0x19)
accel = LIS3DH_new.Accelerometer('spi', spiPort = 0, spiCS = 0)  # spi connection alternative
accel.set_ODR(odr=50, powerMode='normal')
accel.axis_enable(x='on',y='on',z='on')
accel.interrupt_high_low('high')
accel.latch_interrupt('on')
accel.set_BDU('on')
accel.set_scale()


    
t_end = time.time() + 1 
while time.time() < t_end:
                
        x = accel.x_axis_reading()
        y = accel.y_axis_reading()
        z = accel.z_axis_reading()
        print ('x: '+str(x)+' y: '+str(y)+' z: '+str(z))`

Where 'LIS3DH_new' is your LIS3DH.py after the fix

**Comment by owainm713** [comment]
Hi,  I ran your code and it worked fine.  Do you have the LIS3DH CS going to the Pi CE0 (since you are using spiCS = 0 in your code)

**Comment by GawiQ** [comment]
Hi
Turned out it was a faulty CS cable, thanks.

Now I have another headache...
Every few readings I get a jump in value, almost two times more than around 256. I get this on every axle, both sensors, but only with positive values and if an axle is closest to pointing directly up. If it is slightly off this doesn't happen. It looks like an example below:

`508.000000	 12.000000	 0.000000

 252.000000	 12.000000	 4.000000`

**Comment by owainm713** [comment]
That's great that you got it going.

For the 2nd item, do you have any delay in between your set of readings?  If not, try adding a small delay (0.1s) and see how the readings look after that

**Comment by GawiQ** [comment]
I don't have any delays cause I wanted sampling rate to be as high as possible. 
Tried with delays in few configurations ranging from 0.0001s to 1s and it still occurs in every case.

**Comment by GawiQ** [comment]
Looks like when the jump occurs there is a one more '1' instead of '0' to the left of the binary value. 0000000001111111 for 127
0000000000111111 for 63  (8G range)
or
0000000111111100 for 508 
0000000011111100 for 252 (2G range)

But no idea where to go from there :/

**Comment by owainm713** [comment]
So I tried to recreate that issue,  I ran with no delay upto 60 seconds long and at the 2G range  the max and min were within 27 or less for example, z min approx 250 and z max 277, this was over several million readings (every 10 seconds of readings was approx 75k readings)

**Comment by GawiQ** [comment]
I get results like yours only with I2C, shame it isn't fast enough.

**Comment by owainm713** [comment]
that is unfortunate

**Comment by GawiQ** [comment]
So I checked a few configurations and the only one which works fine is with spi0 and max speed set to 10MHz.

The thing is, one sensor is connected through a patch/stranded type cable and the other uses standard/solid(?) type cable.
Only the patch cable connected one works on spi0 and with 10MHz speed, but it doesn't work on spi1. 
Standard cable connected sensor doesn't work properly on either of spi buses and speed makes no difference.

**Comment by owainm713** [comment]
not fully related, but have you played around with the ODR (output data rate) of the sensor,  max being 5kHz if you want the most samples possible

**Comment by owainm713** [comment]
something else I thought of,  have you thought of using the sensor's data ready interrupt capabilities so you only have to communicate with it when there is new data to process?

**Comment by GawiQ** [comment]
I did play with the ODR but it makes no differnce. Did not play with data ready interrupt though. No idea how this works really

**Comment by GawiQ** [comment]
Problem solved!  :)

Shielded patch cable solved the issue. Not a single double value jump during 60s trial - both sensors, one on spi0, the other on spi1, max ODR, no delays. Thanks for all the tips.

**Comment by owainm713** [comment]
Fantastic...I've been playing around with the data ready interrupt and got some good results so far, I may add a new example using it. Also with playing around with the data ready interrupt I can tell the ODR definitely does make a difference in the number of readings the sensor takes per second

Hope your project works well for you

**Comment by GawiQ** [comment]
Yes, the ODR does make a difference in the number of readings per second :)  What I meant was that it didn't make a differnce with te jumping values issue.
Cheers
