### ISSUE TITLE
Meaning of axis_reading

### ISSUE THREAD

**Issue by Sprud00** [owainm713/LIS3DH-Python-Module#2]
Hi,

I am novice in the use of such I2C devices and I have an hard time understanding the readings I get from x_axis_reading() (or any other axis). From what I understand, it should be raw data meaning that value range is ±2^16 and we have to scale it according to the range in g used. The problem is that those values make no sense. With a good shake I read around 50 in raw values. Which is way too low.

Can you help me convert the values?

Thanks.

**Comment by owainm713** [comment]
Hi

With your sensor lying flat on a table,  do you get readings of approximately 0 for the x & y axis and approximately 256 for the z axis?  I'm assuming you are using the +-2g scale setting

For the +-2g scale, with this code the readings will fall between -512 and 511

**Comment by Sprud00** [comment]
Hi,
I've finally figure that out. I was thinking the accelerometer was set at high resolution (12bit) so my scaling was not good. Nevertheless, I found your method for setting it so high resolution, but it seems to have no effect. My understanding is that the twos complement conversion is hard coded at 10 bit. Am I right? I there any other method that I would have to modify in order for the accelerometer to work in high resolution?

Sincerely,

**Comment by owainm713** [comment]
The sensor does provide a 10bit 2s complement number which my module converts to a reading between -512 and 511.  The scale can be changed to either +-2g, +-4g, +-8g or +-16g which will impact the resolution of result provided.
